blank_issues_enabled: true
contact_links:
  - name: "Help, Questions, Ideas, etc."
    url: https://github.com/xilk-org/xilk-xp-web-app-template/discussions
    about: "Post in Discussions instead of opening an issue."
